// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-menu.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload, null, 2) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-menu.ts
var list_menu_default = defineTool({
  name: "list_menu",
  title: "Listar card\xE1pio",
  description: "Lista os produtos ativos do card\xE1pio da UP Esfihas Artesanais (nome, categoria, descri\xE7\xE3o e pre\xE7o). Opcionalmente filtra por categoria ou por texto de busca.",
  inputSchema: {
    categoria: z.string().optional().describe("Filtra por categoria exata, ex: 'Esfihas Salgadas'."),
    busca: z.string().optional().describe("Texto para buscar no nome do produto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ categoria, busca }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    let query = supabaseForUser(ctx).from("produtos").select("id, nome, categoria, descricao, preco").eq("ativo", true).order("categoria").order("nome");
    if (categoria) query = query.eq("categoria", categoria);
    if (busca) query = query.ilike("nome", `%${busca}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, produtos: data ?? [] });
  }
});

// src/lib/mcp/tools/list-delivery-areas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_delivery_areas_default = defineTool2({
  name: "list_delivery_areas",
  title: "Listar bairros atendidos",
  description: "Lista os bairros ativos onde a UP Esfihas Artesanais faz entrega em Florian\xF3polis. A taxa de entrega \xE9 calculada por dist\xE2ncia no checkout.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const { data, error } = await supabaseForUser(ctx).from("bairros").select("id, nome").eq("ativo", true).order("nome");
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, bairros: data ?? [] });
  }
});

// src/lib/mcp/tools/get-store-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_store_status_default = defineTool3({
  name: "get_store_status",
  title: "Status da loja",
  description: "Retorna o hor\xE1rio de funcionamento configurado da loja: dias abertos, hora de abertura, hora de fechamento e eventual override manual (aberto/fechado for\xE7ado).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const { data, error } = await supabaseForUser(ctx).from("horario_funcionamento").select("dias_abertos, dias_semana, hora_abertura, hora_fechamento, override_manual, ativo").limit(1).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Hor\xE1rio de funcionamento n\xE3o configurado.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "Meus pedidos",
  description: "Lista os pedidos do usu\xE1rio autenticado, do mais recente para o mais antigo, com n\xFAmero, status, total, forma de pagamento e itens.",
  inputSchema: {
    limite: z2.number().int().optional().describe("Quantidade m\xE1xima de pedidos a retornar (padr\xE3o 10)."),
    status: z2.string().optional().describe("Filtra por status: pendente, aceito, preparo, saiu_entrega, finalizado, cancelado, aguardando_pagamento.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limite, status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const max = Math.min(Math.max(limite ?? 10, 1), 50);
    let query = supabaseForUser(ctx).from("pedidos").select(
      "id, numero, status, total, subtotal, taxa_entrega, metodo_pagamento, troco, observacao_pagamento, items, endereco, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(max);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, pedidos: data ?? [] });
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_order_default = defineTool5({
  name: "get_order",
  title: "Detalhes do pedido",
  description: "Retorna os detalhes completos de um pedido do usu\xE1rio autenticado, buscando pelo n\xFAmero do pedido.",
  inputSchema: {
    numero: z3.number().int().describe("N\xFAmero sequencial do pedido.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ numero }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const { data, error } = await supabaseForUser(ctx).from("pedidos").select("*").eq("user_id", ctx.getUserId()).eq("numero", numero).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult(`Pedido #${numero} n\xE3o encontrado para este usu\xE1rio.`);
    return textResult(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "yjhrlkwselsqymewpdgc";
var mcp_default = defineMcp({
  name: "up-esfihas-mcp",
  title: "UP Esfihas Artesanais",
  version: "0.1.0",
  instructions: "Ferramentas da UP Esfihas Artesanais (delivery em Florian\xF3polis). Use `list_menu` para consultar o card\xE1pio, `list_delivery_areas` para os bairros atendidos, `get_store_status` para o hor\xE1rio de funcionamento, e `list_my_orders` / `get_order` para os pedidos do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_menu_default, list_delivery_areas_default, get_store_status_default, list_my_orders_default, get_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
